version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db_library
    hostname: db
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-network

  backend:
    build: .
    container_name: backend_library
    hostname: backend
    restart: always
    command: python main.py
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RELOAD=FALSE
    ports:
      - 8000:8000
    networks:
      - db-network
    depends_on:
      - db


networks:
  db-network:
    driver: bridge
